/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppExaminationsRouteImport } from './routes/_app.examinations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAcademicsRouteImport } from './routes/_app.academics'
import { Route as AppExaminationsIndexRouteImport } from './routes/_app.examinations.index'
import { Route as AppAcademicsIndexRouteImport } from './routes/_app.academics.index'
import { Route as AppExaminationsSemesterRouteImport } from './routes/_app.examinations.semester'
import { Route as AppExaminationsRegistrationRouteImport } from './routes/_app.examinations.registration'
import { Route as AppExaminationsMarksRouteImport } from './routes/_app.examinations.marks'
import { Route as AppExaminationsInternalsRouteImport } from './routes/_app.examinations.internals'
import { Route as AppAcademicsTimetableRouteImport } from './routes/_app.academics.timetable'
import { Route as AppAcademicsSubjectsRouteImport } from './routes/_app.academics.subjects'
import { Route as AppAcademicsRegistrationRouteImport } from './routes/_app.academics.registration'
import { Route as AppAcademicsAttendanceCodeRouteImport } from './routes/_app.academics.attendance-code'
import { Route as AppAcademicsAttendanceRouteImport } from './routes/_app.academics.attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppExaminationsRoute = AppExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicsRoute = AppAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AppRoute,
} as any)
const AppExaminationsIndexRoute = AppExaminationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExaminationsRoute,
} as any)
const AppAcademicsIndexRoute = AppAcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAcademicsRoute,
} as any)
const AppExaminationsSemesterRoute = AppExaminationsSemesterRouteImport.update({
  id: '/semester',
  path: '/semester',
  getParentRoute: () => AppExaminationsRoute,
} as any)
const AppExaminationsRegistrationRoute =
  AppExaminationsRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AppExaminationsRoute,
  } as any)
const AppExaminationsMarksRoute = AppExaminationsMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AppExaminationsRoute,
} as any)
const AppExaminationsInternalsRoute =
  AppExaminationsInternalsRouteImport.update({
    id: '/internals',
    path: '/internals',
    getParentRoute: () => AppExaminationsRoute,
  } as any)
const AppAcademicsTimetableRoute = AppAcademicsTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppAcademicsRoute,
} as any)
const AppAcademicsSubjectsRoute = AppAcademicsSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppAcademicsRoute,
} as any)
const AppAcademicsRegistrationRoute =
  AppAcademicsRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AppAcademicsRoute,
  } as any)
const AppAcademicsAttendanceCodeRoute =
  AppAcademicsAttendanceCodeRouteImport.update({
    id: '/attendance-code',
    path: '/attendance-code',
    getParentRoute: () => AppAcademicsRoute,
  } as any)
const AppAcademicsAttendanceRoute = AppAcademicsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppAcademicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/academics': typeof AppAcademicsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/examinations': typeof AppExaminationsRouteWithChildren
  '/feedback': typeof AppFeedbackRoute
  '/profile': typeof AppProfileRoute
  '/academics/attendance': typeof AppAcademicsAttendanceRoute
  '/academics/attendance-code': typeof AppAcademicsAttendanceCodeRoute
  '/academics/registration': typeof AppAcademicsRegistrationRoute
  '/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/academics/timetable': typeof AppAcademicsTimetableRoute
  '/examinations/internals': typeof AppExaminationsInternalsRoute
  '/examinations/marks': typeof AppExaminationsMarksRoute
  '/examinations/registration': typeof AppExaminationsRegistrationRoute
  '/examinations/semester': typeof AppExaminationsSemesterRoute
  '/academics/': typeof AppAcademicsIndexRoute
  '/examinations/': typeof AppExaminationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/profile': typeof AppProfileRoute
  '/academics/attendance': typeof AppAcademicsAttendanceRoute
  '/academics/attendance-code': typeof AppAcademicsAttendanceCodeRoute
  '/academics/registration': typeof AppAcademicsRegistrationRoute
  '/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/academics/timetable': typeof AppAcademicsTimetableRoute
  '/examinations/internals': typeof AppExaminationsInternalsRoute
  '/examinations/marks': typeof AppExaminationsMarksRoute
  '/examinations/registration': typeof AppExaminationsRegistrationRoute
  '/examinations/semester': typeof AppExaminationsSemesterRoute
  '/academics': typeof AppAcademicsIndexRoute
  '/examinations': typeof AppExaminationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/academics': typeof AppAcademicsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/examinations': typeof AppExaminationsRouteWithChildren
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/academics/attendance': typeof AppAcademicsAttendanceRoute
  '/_app/academics/attendance-code': typeof AppAcademicsAttendanceCodeRoute
  '/_app/academics/registration': typeof AppAcademicsRegistrationRoute
  '/_app/academics/subjects': typeof AppAcademicsSubjectsRoute
  '/_app/academics/timetable': typeof AppAcademicsTimetableRoute
  '/_app/examinations/internals': typeof AppExaminationsInternalsRoute
  '/_app/examinations/marks': typeof AppExaminationsMarksRoute
  '/_app/examinations/registration': typeof AppExaminationsRegistrationRoute
  '/_app/examinations/semester': typeof AppExaminationsSemesterRoute
  '/_app/academics/': typeof AppAcademicsIndexRoute
  '/_app/examinations/': typeof AppExaminationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/academics'
    | '/dashboard'
    | '/examinations'
    | '/feedback'
    | '/profile'
    | '/academics/attendance'
    | '/academics/attendance-code'
    | '/academics/registration'
    | '/academics/subjects'
    | '/academics/timetable'
    | '/examinations/internals'
    | '/examinations/marks'
    | '/examinations/registration'
    | '/examinations/semester'
    | '/academics/'
    | '/examinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/academics/attendance'
    | '/academics/attendance-code'
    | '/academics/registration'
    | '/academics/subjects'
    | '/academics/timetable'
    | '/examinations/internals'
    | '/examinations/marks'
    | '/examinations/registration'
    | '/examinations/semester'
    | '/academics'
    | '/examinations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/academics'
    | '/_app/dashboard'
    | '/_app/examinations'
    | '/_app/feedback'
    | '/_app/profile'
    | '/_app/academics/attendance'
    | '/_app/academics/attendance-code'
    | '/_app/academics/registration'
    | '/_app/academics/subjects'
    | '/_app/academics/timetable'
    | '/_app/examinations/internals'
    | '/_app/examinations/marks'
    | '/_app/examinations/registration'
    | '/_app/examinations/semester'
    | '/_app/academics/'
    | '/_app/examinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/examinations': {
      id: '/_app/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof AppExaminationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academics': {
      id: '/_app/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AppAcademicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/examinations/': {
      id: '/_app/examinations/'
      path: '/'
      fullPath: '/examinations/'
      preLoaderRoute: typeof AppExaminationsIndexRouteImport
      parentRoute: typeof AppExaminationsRoute
    }
    '/_app/academics/': {
      id: '/_app/academics/'
      path: '/'
      fullPath: '/academics/'
      preLoaderRoute: typeof AppAcademicsIndexRouteImport
      parentRoute: typeof AppAcademicsRoute
    }
    '/_app/examinations/semester': {
      id: '/_app/examinations/semester'
      path: '/semester'
      fullPath: '/examinations/semester'
      preLoaderRoute: typeof AppExaminationsSemesterRouteImport
      parentRoute: typeof AppExaminationsRoute
    }
    '/_app/examinations/registration': {
      id: '/_app/examinations/registration'
      path: '/registration'
      fullPath: '/examinations/registration'
      preLoaderRoute: typeof AppExaminationsRegistrationRouteImport
      parentRoute: typeof AppExaminationsRoute
    }
    '/_app/examinations/marks': {
      id: '/_app/examinations/marks'
      path: '/marks'
      fullPath: '/examinations/marks'
      preLoaderRoute: typeof AppExaminationsMarksRouteImport
      parentRoute: typeof AppExaminationsRoute
    }
    '/_app/examinations/internals': {
      id: '/_app/examinations/internals'
      path: '/internals'
      fullPath: '/examinations/internals'
      preLoaderRoute: typeof AppExaminationsInternalsRouteImport
      parentRoute: typeof AppExaminationsRoute
    }
    '/_app/academics/timetable': {
      id: '/_app/academics/timetable'
      path: '/timetable'
      fullPath: '/academics/timetable'
      preLoaderRoute: typeof AppAcademicsTimetableRouteImport
      parentRoute: typeof AppAcademicsRoute
    }
    '/_app/academics/subjects': {
      id: '/_app/academics/subjects'
      path: '/subjects'
      fullPath: '/academics/subjects'
      preLoaderRoute: typeof AppAcademicsSubjectsRouteImport
      parentRoute: typeof AppAcademicsRoute
    }
    '/_app/academics/registration': {
      id: '/_app/academics/registration'
      path: '/registration'
      fullPath: '/academics/registration'
      preLoaderRoute: typeof AppAcademicsRegistrationRouteImport
      parentRoute: typeof AppAcademicsRoute
    }
    '/_app/academics/attendance-code': {
      id: '/_app/academics/attendance-code'
      path: '/attendance-code'
      fullPath: '/academics/attendance-code'
      preLoaderRoute: typeof AppAcademicsAttendanceCodeRouteImport
      parentRoute: typeof AppAcademicsRoute
    }
    '/_app/academics/attendance': {
      id: '/_app/academics/attendance'
      path: '/attendance'
      fullPath: '/academics/attendance'
      preLoaderRoute: typeof AppAcademicsAttendanceRouteImport
      parentRoute: typeof AppAcademicsRoute
    }
  }
}

interface AppAcademicsRouteChildren {
  AppAcademicsAttendanceRoute: typeof AppAcademicsAttendanceRoute
  AppAcademicsAttendanceCodeRoute: typeof AppAcademicsAttendanceCodeRoute
  AppAcademicsRegistrationRoute: typeof AppAcademicsRegistrationRoute
  AppAcademicsSubjectsRoute: typeof AppAcademicsSubjectsRoute
  AppAcademicsTimetableRoute: typeof AppAcademicsTimetableRoute
  AppAcademicsIndexRoute: typeof AppAcademicsIndexRoute
}

const AppAcademicsRouteChildren: AppAcademicsRouteChildren = {
  AppAcademicsAttendanceRoute: AppAcademicsAttendanceRoute,
  AppAcademicsAttendanceCodeRoute: AppAcademicsAttendanceCodeRoute,
  AppAcademicsRegistrationRoute: AppAcademicsRegistrationRoute,
  AppAcademicsSubjectsRoute: AppAcademicsSubjectsRoute,
  AppAcademicsTimetableRoute: AppAcademicsTimetableRoute,
  AppAcademicsIndexRoute: AppAcademicsIndexRoute,
}

const AppAcademicsRouteWithChildren = AppAcademicsRoute._addFileChildren(
  AppAcademicsRouteChildren,
)

interface AppExaminationsRouteChildren {
  AppExaminationsInternalsRoute: typeof AppExaminationsInternalsRoute
  AppExaminationsMarksRoute: typeof AppExaminationsMarksRoute
  AppExaminationsRegistrationRoute: typeof AppExaminationsRegistrationRoute
  AppExaminationsSemesterRoute: typeof AppExaminationsSemesterRoute
  AppExaminationsIndexRoute: typeof AppExaminationsIndexRoute
}

const AppExaminationsRouteChildren: AppExaminationsRouteChildren = {
  AppExaminationsInternalsRoute: AppExaminationsInternalsRoute,
  AppExaminationsMarksRoute: AppExaminationsMarksRoute,
  AppExaminationsRegistrationRoute: AppExaminationsRegistrationRoute,
  AppExaminationsSemesterRoute: AppExaminationsSemesterRoute,
  AppExaminationsIndexRoute: AppExaminationsIndexRoute,
}

const AppExaminationsRouteWithChildren = AppExaminationsRoute._addFileChildren(
  AppExaminationsRouteChildren,
)

interface AppRouteChildren {
  AppAcademicsRoute: typeof AppAcademicsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExaminationsRoute: typeof AppExaminationsRouteWithChildren
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicsRoute: AppAcademicsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExaminationsRoute: AppExaminationsRouteWithChildren,
  AppFeedbackRoute: AppFeedbackRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
